import testlist.myExceptions.ExceptionNoFound;

public class TestList {
    public static void main(String[] args) throws ExceptionNoFound {
        
    }
}
